# Generated by Django 3.1.6 on 2021-03-02 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Electricity', models.CharField(max_length=256)),
                ('Water', models.CharField(max_length=500)),
            ],
        ),
    ]
