# Generated by Django 3.1.6 on 2021-03-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentaldetails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Electricity', models.CharField(max_length=256)),
                ('Water', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='rental',
            name='Electricity',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='Water',
        ),
    ]
