# Generated by Django 3.1.6 on 2021-03-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentaldetails', '0002_auto_20210302_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='Detail',
            name='Deposit',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='Detail',
            name='Rent',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='Detail',
            name='Bathroom',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='Detail',
            name='Floors',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='Detail',
            name='Image_url',
            field=models.CharField(default=0, max_length=2090),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='Detail',
            name='Location',
            field=models.CharField(default=0, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='Detail',
            name='Name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='Detail',
            name='no_of_rooms',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='Detail',
            name='Roof',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='Detail',
            name='Walls',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rental',
            name='Contacts',
            field=models.CharField(default=0, max_length=350),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rental',
            name='Total_no_of_units',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rental',
            name='Type_0f_Rental',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rental',
            name='Name_of_rental',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
