# Generated by Django 3.1.6 on 2021-03-02 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentaldetails', '0003_auto_20210302_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='Detail',
            name='no_of_rooms',
        ),
    ]
