# Generated by Django 3.1.6 on 2021-03-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentaldetails', '0004_remove_detail_no_of_rooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='Detail',
            name='Rent',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='Contacts',
        ),
        migrations.AddField(
            model_name='Detail',
            name='Contacts',
            field=models.CharField(default=0, max_length=350),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rental',
            name='Rent',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rental',
            name='Image_url',
            field=models.CharField(default=0, max_length=2090),
            preserve_default=False,
        ),
    ]
