# Generated by Django 3.1.6 on 2021-03-02 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentaldetails', '0005_auto_20210302_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='Type_0f_Rental',
            new_name='Type_of_rental',
        ),
    ]
