# Generated by Django 3.1.6 on 2021-03-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentaldetails', '0007_auto_20210317_1428'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Detail',
        ),
        migrations.AddField(
            model_name='rental',
            name='Bathroom',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rental',
            name='Contacts',
            field=models.CharField(default=0, max_length=350),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rental',
            name='Deposit',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rental',
            name='Electricity',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rental',
            name='Floors',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rental',
            name='Image_url1',
            field=models.CharField(default=0, max_length=2090),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rental',
            name='Location',
            field=models.CharField(default=0, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rental',
            name='Name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rental',
            name='Roof',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rental',
            name='Walls',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rental',
            name='Water',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
