# Generated by Django 4.0.3 on 2022-03-17 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentaldetails', '0008_auto_20210317_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
