# Generated by Django 4.2.4 on 2023-08-03 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentaldetails', '0010_bookrental_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrental',
            name='Name_of_rental',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
